runtime: python39

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /js
  static_files: /js
  upload: /js

- url: /(.+)
  static_files: dist/\1
  upload: dist/(.*)

- url: /
  static_files: dist/index.html
  upload: dist/index.html

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
